remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

title: "Jaehun Baek | CS @ Georgia Tech"
description: "Personal website of Jaehun Baek, a Computer Science student at Georgia Tech."

author:
  name: "Jaehun Baek"
  avatar: "/assets/images/Baek_Jaehun.jpg" # path to my photo
  bio: "Computer Science student at Georgia Tech."
  location: "Atlanta, GA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jbaek90@gatech.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaeHbk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jaehunbaek"